function txt = instructionText(mode)
switch mode
    case 'visual'
        txt = ['Thank you for your participation in the experiment!\n',...
            'You will be soon presented with sentences whose words will appear\none after the other on the screen.\n',...
            'Your task is to carefully read each sentence and\nrepeat it when a cue appears on the screen. \n',...
            'Please do not start repeating before the cue appears. \nThe cue will be a small star (*) at the center of the screen.\n',...
            '\n',...
            'Once you finish repeating the sentence, you can press \na key on the keyboard or the mouse to continue to the next sentence.\n',...
            '\n',...
            'This is an important scientific experiment about brain function!\nPlease remain focused as much as possible throughout the experiment.\n',...
            'Thank you!\n'];
    case 'audio'
        txt = ['Thank you for your participation in the experiment!\n',...
            'You will be soon presented with sentences one after the other.\n',...
            'Your task is to listen carefully to each sentence \nand repeat it when a cue appears on the screen. \n',...
            'Please do not start repeating before the cue appears. \nThe cue will be a small star (*) at the center of the screen.\n',...
            '\n',...
            'Once you finish repeating the sentence, you can press \na key on the keyboard or the mouse to continue to the next sentence.\n',...
            '\n',...
            'This is an important scientific experiment about brain function!\nPlease remain focused as much as possible throughout the experiment.\n',...
            'Thank you!\n'];
end

txt = [txt,'\n\n\n Press Any Key to Continue'];